= solr-metamorph-entity-processor
:toc:

A add-on for the Apache Solr Data Import Handler.

This project adds an entity processor that handles bibliographic records.
It supports the link:https://github.com/metafacture/metafacture-core/wiki/Metamorph-User-Guide[metamorph] DSL for data
extraction.

== Installation

----
mvn package
----

Produces _solr-metamorph-entity-processor-VERSION.jar_ in _target_ .

=== Solr Integration

_Assuming a fresh Solr installation._

==== Metamorph Installation

Copy the folders in `examples/server` into the `server` directory of your Solr installation.

The following files will be added to the Solr server:

* metamorph and its dependencies (into `lib`)
* XSD schemata needed by metamorph (into `schemata`)
* property files needed by metamorph (into `resources`)

NOTE::
This is a workaround.
The proper way to include a third-party library to Solr is the `contrib` directory.
A integration of Metamorph with the lib statement (see next section) failed due to
missing schema and property files and not loadable classes.
Adding those files directly to the server resolved the issue.

==== Plugin Installation

Place the jar in the _dist_ footnote:[The folder resides inside the root directory.]
directory of your Solr installation.

==== Data Import Handler Configuration

Enable the Data Import Handler and the processor by adding the following
_lib_ statements to the `solrconfig.xml` of your _config set_:

----
<lib dir="${solr.install.dir:../../../..}/dist/" regex="solr-dataimporthandler-.*\.jar" />

<lib dir="${solr.install.dir:../../../..}/dist/" regex="solr-metamorph-entity-processor-.*\.jar" />
----

Add the _/dataimport_ request handle to the `solrconfig.xml`:

----
  <requestHandler name="/dataimport" class="solr.DataImportHandler">
    <lst name="defaults">
      <str name="config">solr-data-config.xml</str>
    </lst>
  </requestHandler>
----

A example `solr-data-config.xml` is located in `examples/configsets/demo/conf`.

==== Example Config Set

The folder `examples/configsets` contains a modified version of the _default_ config set shipped with Solr.

* `solrconfig.xml` with the data import handler enabled (see above).
* `morph.xml` metamorph definition file that reads the field `001` and renames it to `idn`.
* `solr-data-config.xml`:
** A file list reader for the `/tmp` directory.
** A marc21 entity processor that uses _morph.xml_ to process those files.

A example file for the `/tmp` directory is located in `examples/tmp`.

== Metamorph Entity Processor

This MetamorphEntityProcessor reads all content from the data source on a record
by record basis. This processor may handle compressed input streams,
if the consumed data source is a _BinFileDataSource_.

Each record is processed by a metafacture pipeline that uses metamorph to extract fields.

The Metamorph Entity Processor has the following attributes:

url::
_Required._ A attribute that specifies the location of the input file in a way that is compatible with the configured data source.

inputFormat::
_Required._  The format supplied by the data source.

Formats:::
* marc21
** Pre-processing records by replacing _newline_ and _carriage return_ with a space
* default
** No pre-processing
** One record per line

morphDef::
_Required._ The metamorph definition file that is used for field extraction.
If the input is a list of files (separated by a comma), the data get passed
from one metamorph file to another.
Those files are located inside the config sets _conf_ directory.

includeFullRecord::
An _optional_ attribute that adds the parsed record to the row within the `fullRecord` field.

onError::
By default, the MetamorphEntityProcessor will stop processing documents if it finds one that generates an error.
If you define _onError_ to "skip", the MetamorphEntityProcessor will instead skip documents that fail processing and
log a debug message that the document was skipped.

For example:

[source,xml]
----
<entity name="morph"
        processor="org.culturegraph.solr.handler.dataimport.MetamorphEntityProcessor"
        url="path/to/file.marc21"
        inputFormat="marc21"
        morphDef="morph.xml,morph2.xml"
        includeFullRecord="true"
        onError="skip">
  <field column="identifier" name="id"/>
  <field column="fullRecord" name="fullRecord_s"/>
</entity>
----

The used metamorph definitions:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<!-- morph.xml -->
<metamorph xmlns="http://www.culturegraph.org/metamorph" version="1">
    <rules>
        <data name="idn" source="001"/>
    </rules>
</metamorph>
----

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<!-- morph2.xml -->
<metamorph xmlns="http://www.culturegraph.org/metamorph" version="1">
    <rules>
        <data name="identifier" source="idn"/>
    </rules>
</metamorph>
----

== Import

Run a full-import:

----
curl -s http://localhost:1111/solr/demo/dataimport?command=full-import
----

Check status:

----
curl -s http://localhost:1111/solr/demo/dataimport?command=status
----

NOTE::
The admin UI provides a link:https://lucene.apache.org/solr/guide/7_4/dataimport-screen.html[Dataimport Screen] .

== References

* link:https://lucene.apache.org/solr/guide/7_4/uploading-structured-data-store-data-with-the-data-import-handler.html[Solr Ref Guide: Data Import Handler]

== Appendix

=== Metamorph IR To Row Conversion

A record processed by metamorph will be transformed into a intermediate representation (IR)
that consists of the following elements:

* Record
* Entity
* Literal

A row processed by Solr is a map that consists of key-value or key-list pairs.

.IR
----
startRecord("001")
literal("date", "20181001")
startEntity("person")
literal("lastname", "Unkown")
endEntity()
literal("cat", "human")
literal("cat", "person")
endRecord()
----

.Row (Represented as JSON)
----
{
  "cat": ["human", "person"]
  "date": "20181001"
  "personLastname": "Unkown"
}
----

The following rules are applied to convert a _IR_ to a _Row_:

* Record id will be ignored
* Literals with the same name form a list
* Literal names in entities are prefixed with the entity name in CamelCase